apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://fluent.github.io/helm-charts"
      chart: fluent-bit
      targetRevision: 0.46.7
      helm:
        valueFiles:
          - $values/infra-apps/values/fluent-values.yaml
    - repoURL: "git@gitlab.com:roeyw/portf_gitops.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true